require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - 'traxor.gemspec'
    - 'Guardfile'
