AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - 'traxor.gemspec'
    - 'Guardfile'

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'
