sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
before_install: gem install bundler
script: "bin/rspec"
