sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.4
gemfile:
  - gemfiles/active_support_5_0.gemfile
  - gemfiles/active_support_5_1.gemfile
  - gemfiles/active_support_5_2.gemfile
before_install: gem install bundler
script: "bin/rspec"
