version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          RAILS_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Bundle Install
          command: bundle install --deployment --jobs 4 --retry 3

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: RSpec
          command: |
            mkdir results
            bundle exec rspec spec --order random --profile --format documentation --format RspecJunitFormatter --out results/rspec.xml
            ./cc-test-reporter format-coverage -t simplecov coverage/.resultset.json
            ./cc-test-reporter upload-coverage

      - store_test_results:
          path: results
      - store_artifacts:
          path: results
      - store_artifacts:
          path: coverage
